### ISSUE TITLE
Error while executing automation automation.daily_snapshot_clean_up. Unknown error for call_service at pos 1: 

### ISSUE THREAD

**Issue by quantummobile** [tmonck/clean_up_snapshots#1]
Hi,

I am getting errors while trying to execute automation:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 431, in action
    await script_obj.async_run(variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 151, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 235, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 318, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 98, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/clean_up_snapshots_service/__init__.py", line 105, in async_handle_clean_up
    for snapshot in snapshots:
TypeError: 'NoneType' object is not iterable`

**Comment by tmonck** [comment]
Thanks I will look into this.

**Comment by tmonck** [comment]
@quantummobile there should be another log above that one that is tells you the snapshots it found. Are there any snapshots in that log statement or does it say None? I am putting in a fix for the exception you are having but want to make sure that the problem isn't when trying to get your snapshots causing the list to be None.

**Comment by quantummobile** [comment]
@tmonck is this the one?

`'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/clean_up_snapshots_service/__init__.py", line 105, in async_handle_clean_up
    for snapshot in snapshots:
TypeError: 'NoneType' object is not iterable`

**Comment by tmonck** [comment]
It would be above that. I am going to merge in my change and release a new version. I'll keep this open to make sure it resolves the exception that's being thrown, but if your snapshots don't get cleaned up then you will need to let me know so we can work through why the api call isn't returning any snapshots.

**Comment by tmonck** [comment]
@quantummobile the error you pasted should not happen again. Please let me know if the snapshots do not clean up. We will work through the api not returning you any snapshots.

**Comment by quantummobile** [comment]
Failed config
  General Errors: 
    - Component error: clean_up_snapshots_service - No module named 'dateutil'

**Comment by quantummobile** [comment]
Now I'm getting this error:

`Client error on calling get snapshots
Traceback (most recent call last):
  File "/config/custom_components/clean_up_snapshots_service/__init__.py", line 44, in async_get_snapshots
    resp = await session.get(hassio_url + 'snapshots', headers=headers, ssl=not isgoodipv4(urlparse(hassio_url).netloc))
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 466, in _request
    ssl=ssl, proxy_headers=proxy_headers, traces=traces)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 286, in __init__
    self.update_host(url)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 340, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: 192.168.xxx.xxx/api/hassio/snapshots`

**Comment by tmonck** [comment]
So can you try adding "http://" infront of your url that you have in the configuration.yaml for "host"
ex: "http://192.168.xxx.xxx"

**Comment by quantummobile** [comment]
Did that, got these errors:

`Client error on calling get snapshots
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 954, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 941, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 494, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.xxx.xxx', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/clean_up_snapshots_service/__init__.py", line 44, in async_get_snapshots
    resp = await session.get(hassio_url + 'snapshots', headers=headers, ssl=not isgoodipv4(urlparse(hassio_url).netloc))
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 992, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 931, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.xxx.xxx:80 ssl:False [Connect call failed ('192.168.xxx.xxx', 80)]`

**Comment by tmonck** [comment]
Looks like it's trying to connect to Port 80. You would need the Port of hassio. This defaults to 8123. I don't add the Port for hassio by default.

**Comment by quantummobile** [comment]
OK, I added port number to the host address. Now I get these:

`Client error on calling get snapshots
Traceback (most recent call last):
  File "/config/custom_components/clean_up_snapshots_service/__init__.py", line 44, in async_get_snapshots
    resp = await session.get(hassio_url + 'snapshots', headers=headers, ssl=not isgoodipv4(urlparse(hassio_url).netloc))
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 497, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 844, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 588, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None`

**Comment by grahamw72** [comment]
Was having similar issue. Found that if you set the following things will work with v0.2

host: http://xx.xx.xx.xx:8123
token: abcdefghi......

Please note: no “ “ around the token data.
Also supports !secret ... if you are so inclined.

**Comment by quantummobile** [comment]
> Was having similar issue. Found that if you set the following, things will work with v0.2
> 
> host: http://xx.xx.xx.xx:8123
> token: abcdefghi......
> 
> Please note: no “ “ around the token data.
> Also supports !secret ... if you are so inclined.

Everything is set exactly the same on my side, but the issue remains.

**Comment by tmonck** [comment]
If you put the url you are using in the config into a browser are you taken to the login screen? If you have postman you try to make the api call? To make the api call you would put token in the authorization header like so "Authorization   Bearer {token}" the request is a GET and the url would be http://xxx.xx.xx.xx:8123/api/hassio/snapshots.

**Comment by quantummobile** [comment]
Solved. It should have been https instead http.
Thanks.
