### ISSUE TITLE
Error with deleting snapshots

### ISSUE THREAD

**Issue by inverse** [tmonck/clean_up_snapshots#14]
When trying to use this extension I'm getting the following error:

```bash
2020-12-26 23:41:55 INFO (MainThread) [custom_components.clean_up_snapshots_service] Attempting to remove snapshot: slug=slug_value
2020-12-26 23:41:55 ERROR (MainThread) [custom_components.clean_up_snapshots_service] Client error on calling delete snapshot
Traceback (most recent call last):
  File "/config/custom_components/clean_up_snapshots_service/__init__.py", line 69, in async_remove_snapshots
    resp = await session.post(hassio_url + 'snapshots/' + snapshot['slug'] + "/remove", headers=headers, ssl=shouldVerifySsl(hassio_url))
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 632, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1002, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://hassio.beachi:8123/api/hassio/snapshots/slug_value/remove')
```

Running hassio install with Home Assistant 2020.12.1

Let me know if you need anymore info.

**Comment by tmonck** [comment]
I'll take a look. I just upgraded. So I'll try and replicate also.

**Comment by inverse** [comment]
@tmonck Weirdly this issue doesn't exist today and it looks like it's working. We can close this I think.

p.s thanks for doing this!

**Comment by tmonck** [comment]
Thanks! Glad it's working now. Still gonna try and figure out why you got it that previously
