### ISSUE TITLE
404 finding remove path

### ISSUE THREAD

**Issue by 715Steve** [tmonck/clean_up_snapshots#26]
Script will find the slugs now and count correctly. When attempting to delete a slug I am seeing a 404 error:

2022-04-17 11:28:59 INFO (MainThread) [custom_components.clean_up_snapshots_service] Stale Snapshots: [{'slug': '8c3be962', 'name': 'DailyBackup: Sunday, April 10, 2022', 'date': '2022-04-10T13:40:39.048521+00:00', 'type': 'full', 'size': 1931.49, 'protected': False, 'compressed': True, 'content': {'homeassistant': True, 'addons': ['core_samba', 'core_letsencrypt', 'a0d7b954_appdaemon', 'a0d7b954_bitwarden', 'a0d7b954_esphome', 'core_configurator', 'a0d7b954_vscode', 'core_zwave_js', 'a0d7b954_portainer', 'a0d7b954_spotify', 'a0d7b954_logviewer', 'a0d7b954_motioneye', 'core_check_config', 'a0d7b954_example', 'local_vlc', 'a0d7b954_nodered', 'a0d7b954_tor', 'a0d7b954_adguard', 'a0d7b954_influxdb', 'a0d7b954_grafana', 'a0d7b954_glances', 'core_mariadb', 'a0d7b954_phpmyadmin', 'core_mosquitto'], 'folders': ['share', 'addons/local', 'ssl', 'media']}}]
2022-04-17 11:28:59 INFO (MainThread) [custom_components.clean_up_snapshots_service] Attempting to remove snapshot: slug=8c3be962
2022-04-17 11:28:59 ERROR (MainThread) [custom_components.clean_up_snapshots_service] Client error on calling delete snapshot
Traceback (most recent call last):
  File "/config/custom_components/clean_up_snapshots_service/__init__.py", line 70, in async_remove_snapshots
    resp = await session.post(hassio_url + f"{BACKUPS_URL_PATH}/" + snapshot['slug'] + "/remove", headers=headers, ssl=shouldVerifySsl(hassio_url))
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 640, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://xxxxxxxxxxxxxx.com:8123/api/hassio/backups/8c3be962/remove')

**Comment by tmonck** [comment]
taking a look

**Comment by tmonck** [comment]
Published 0.9.1. I will also validate again on my system. Not sure why i didn't see it right away

**Comment by tmonck** [comment]
Verified. Let me know if you continue to see an issue.

**Comment by 715Steve** [comment]
Concur...Fixed!  Thanks for the useful script!
